Ryan Ellis
COSC 220-003
Lab #7
"Ackerman's Function"- Output and Observations

Main Program:
#include <iostream>
using namespace std;

int A(int, int);

int main(){

cout<< "---Ackerman's Function---"<<endl;
    
    cout << A(0,0)<<endl;
    cout << A(0,1)<<endl;
    cout << A(1,1)<<endl;
    cout << A(1,2)<<endl;
    cout << A(1,3)<<endl;
    cout << A(2,2)<<endl;
    cout << A(3,2)<<endl;
    cout << A(4,1)<<endl;
    cout << A(4,2)<<endl;  // error seg fault
    
     return 0;
}

int A(int val, int val2){

    if(val == 0 || val2 == 0){
        if (val == 0)
            return (val2 + 1);
        
        else if(val2 == 0)
            return A(val - 1,1);
    }
    else
        return A(val - 1, A(val, val2 - 1));
   return -1;
}

Output:
re79380@hpcl1-2:~/Documents/COSC220/Lab7$ ./prog 
---Ackerman's Function---
1
2
3
4
5
7
29
65533
Segmentation fault

Observations:
This code seems to run pretty well on the first few runs of the recursion. However once it reaches the 9th iteration it seems to get bogged down pretty heavily and lags the runtime of the program significantly. Then the program proceeds to run into a segmentation fault within a lengthy amount of time, indicating that the stack does not have the ability to hold the processes needed to run the recursion.  

